version: '3.7'

services:
  openapi_nbrb:
    image: openapi/nbrb
    command: -l debug
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5000
    ports:
      - "5000:5000"
